### ISSUE TITLE
[Feature] 판매글(Article)에 동네(Region) 정보 추가

### ISSUE THREAD

**Issue by sangrimlee** [woowa-techcamp-2022/web-fleemarket-05#33]
## 🔨 요구사항

- 판매글에 동네 정보 추가

## ✅ 작업리스트

- [x] Article과 Region간의 관계 추가하기
- [x] Article 생성시에 동네 정보 추가하기 (수정시에는 어떻게 할 지 고민하기)
- [x] Article 조회시에 동네별로 필터링하는 기능 추가하기
- [x] Article 조회시에 동네 정보 추가하기

## 🚧 참고사항
- 프론트엔드에서 판매 글에 동네 글을 어떻게 선택하는지 정할 필요성이 있어요.
- 당근마켓과 같은 경우는 우선 현재 선택된 지역의 글로 올려져요. 대신, 보여줄 동네를 설정해줄 수 있어요. 하지만, 글을 올린 시점의 선택한 동네기준으로 반경 동네를 설정하는 기능이에요.
- 그래서 동네를 변경할 수 있는 기능을 넣을지 넣는다면 어떤식으로 할 지 고민이 필요해요.

![당근마켓지역선택](https://user-images.githubusercontent.com/56021431/185815546-5ebd775e-42f3-4537-be2b-6920140bd6a8.jpg)

## ⏰ 예상 소요 시간

1시간 30분

**Comment by Hyeondoonge** [comment]
1. 새로운 글을 등록할 때 사용자의 지역인지 확인하는 로직을 추가하는게 좋을까요?
- 로직에 따라 다를 것 같긴하네요!
- 클라이언트에서 동네 정보 보내주기 vs 서버에서  access token을 통해 얻는 user 정보에서 동네 정보 얻기
- 전자는 검증이 필요할테고 후자는 필요없어 보이네요.
- 

3. 이미 올린 글을 수정할 때 동네 정보도 수정할 수 있도록 하는게 좋을까요?

5. 보여줄 동네 설정 기능?
- 지금 db 구조상으로 반경기준으로 보여줄 동네를 가져오는 건 안될 것 같은데 그럼 구조를 조금 바꾸고 기능을 추가해야겠네요!
- 반경기준으로 서버에서 클라이언트로 주변 동네를 보여줄 수도 있지만, 
- 더 쉽게 가려면 사용자가 직접 주변 동네를 검색해서 추가하는 방법도 있을 것 같아요.
