### ISSUE TITLE
[Bug] 로딩인디케이터가 깜빡이는 문제

### ISSUE THREAD

**Issue by Hyeondoonge** [woowa-techcamp-2022/web-fleemarket-05#85]
## 🔨 버그설명
동네를 등록하거나 삭제를 하면 짧게 로딩 인디케이터가 보여져서 불편함이 느껴졌습니다. ㅠㅠ
개인적으로 일반앱에서는 로딩 인디케이터를 체감해서 못해서인지 오히려 사용자 경험을 떨어뜨리는 것 같다는 느낌을 받았어요.
같이 개선책을 고민해보면 좋을 것 같아요!
![Aug-27-2022 17-58-55](https://user-images.githubusercontent.com/55647436/187023246-41fc6c47-1781-41e1-ad66-6337057838bc.gif)

**Comment by sangrimlee** [comment]
로딩 인디케이터가 생기는 이유는 아마도 recoil fetching 작업이 진행되서 일거에요.

그래서 아마도 동네를 선택했을 때 유저 정보를 fetch해오는 것 같은데 fetch하지말고 setter로 recoil 상태를 바꾸어 주거나, Suspense Fallback을 다른 것으로 바꾸면 해결할 수 있을 것 같아요.

**Comment by Hyeondoonge** [comment]
감사합니다!!
지금은 문제가 사라져서, 또 문제가 발생하면 반영해볼게요!

**Comment by sangrimlee** [comment]
AsyncBoundary를 통해 해결하였어요!
